---
title: "Figure 2: Corynebacterium"
output: html_notebook
---

```{r}
library(phyloseq)
library(ggplot2)
library(tidyverse)
library(plotly)
library(ggpubr)
library(readxl)
library(ggplot2)
library(biomformat)
library(dplyr)
library(openxlsx)
library(vegan)
library(reshape2)  
```

```{r}
#imported biom file into phyloseq object
bracken.genera.phy <- import_biom("bracken_genus.biom", parseFunction = parse_taxonomy_greengenes)
bracken.genera.phy <- subset_taxa(bracken.genera.phy, !is.na(Phylum))
bracken.genera.phy <- subset_taxa(bracken.genera.phy, !Kingdom %in% c('Archaea'))
bracken.genera.phy <- subset_taxa(bracken.genera.phy, !Genus %in% c('Homo', 'Toxoplasma', 'Babesia', 'Leishmania'))

#fix sample names to remove _bracken_genuses
 sample_names(bracken.genera.phy) = stringr::str_remove_all(sample_names(bracken.genera.phy), "_bracken_genuses")

map = read.csv("data_files/all_ccca_data.csv")
rownames(map) = map$library_id

#convert to phyloseq
map = sample_data(map)
rownames(map) = map$library_id

#remove "_bracken_genuses" from sample names in the map object
map$library_id <- stringr::str_remove_all(map$library_id, "_bracken_genuses")

generaphy = merge_phyloseq(bracken.genera.phy, map)

#remove Vx sample with less reads than controls
generaphy <- subset_samples(generaphy, library_id != "Met6532") 

#filter samples based on site_specific
generaphy <- subset_samples(generaphy, site_specific %in% c('Vx', 'Oc', 'Vf', 'Ic'))
```

get rid of Species NA column
```{r}
tax_data <- tax_table(generaphy)

tax_df <- as.data.frame(tax_data)

if("Species" %in% colnames(tax_df)){
  tax_df$Species <- NULL}

#convert back to matrix and update the tax_table in phyloseq object
new_tax_table <- tax_table(as.matrix(tax_df))

#replace the existing tax_table in the phyloseq object with the new one
tax_table(generaphy) <- new_tax_table
```

```{r}
#add sample depth to the mapping table
sample_data(generaphy)$sample_sums = sample_sums(generaphy)
```

```{r}
#filter for CCCA
generaphy_CCCA <- subset_samples(generaphy, group_id == "CCCA" & library_id != "Met6532")

#calculate relative abundance for CCCA
generaphy_CCCA_relative_abundance <- transform_sample_counts(generaphy_CCCA, function(x) x / sum(x))

otu_df_CCCA <- otu_table(generaphy_CCCA_relative_abundance)

#define the criteria: taxa (rows) where at least 5% of the samples (columns) have a value >= 0.001 (0.1%)
criteria <- rowSums(otu_df_CCCA >= 0.001) >= ncol(otu_df_CCCA) * 0.05

#use prune_taxa with the logical vector to filter the phyloseq object
generaphy_CCCA_selected <- prune_taxa(criteria, generaphy_CCCA_relative_abundance)
```

```{r}
#filter for Control
generaphy_Control <- subset_samples(generaphy, group_id == "Control")

#calculate relative abundance for Control
generaphy_Control_relative_abundance <- transform_sample_counts(generaphy_Control, function(x) x / sum(x))

otu_df_Control <- otu_table(generaphy_Control_relative_abundance)

#define the criteria: taxa (rows) where at least 10% (5%) of the samples (columns) have a value >= 0.001
criteria <- rowSums(otu_df_Control >= 0.001) >= ncol(otu_df_Control) * 0.05

#use prune_taxa with the logical vector to filter the phyloseq object
generaphy_Control_selected <- prune_taxa(criteria, generaphy_Control_relative_abundance)
```

```{r}
#merge the two phyloseq objects
generaphy_filtered <- merge_phyloseq(generaphy_CCCA_selected, generaphy_Control_selected)

#checking dimensions of the original phyloseq object vs the merged phyloseq object
print(dim(otu_table(generaphy)))

print(dim(otu_table(generaphy_filtered)))
```

```{r}
#extract taxa present in generaphy_filtered
taxa_filtered <- taxa_names(generaphy_filtered)

#subset generaphy by these taxa to get raw read counts for the same set of taxa
genera_rescuedphy <- prune_taxa(taxa_filtered, generaphy)
```

```{r}
Vx_generaphy_filtered = subset_samples(genera_rescuedphy, !(site_specific %in% c("Ctrl", "PrepCtrl", "Ic", "Vf", "Oc")))
Vx_generaphy_filtered <- subset_samples(Vx_generaphy_filtered, library_id != "Met6532")

tax_table <- tax_table(Vx_generaphy_filtered)

tax_table(Vx_generaphy_filtered) <- tax_table

#calculate Relative Abundances
rel_abundance_ps <- transform_sample_counts(Vx_generaphy_filtered, function(x) x / sum(x))

rel_abundance_otu <- otu_table(rel_abundance_ps)

rel_abundance_df <- as.data.frame(as.matrix(rel_abundance_otu))

rel_abundance_df <- rel_abundance_df[ rowSums(rel_abundance_df) != 0, ]
```

```{r}
#Extract genus information and Tax_IDs from tax_table
genus_vector <- tax_table@.Data[, "Genus"]
tax_ids <- rownames(tax_table)

#Create a named vector for genus mapping
named_genus_vector <- setNames(genus_vector, tax_ids)

#Add Genus column to rel_abundance_df
rel_abundance_df$Genus <- named_genus_vector[rownames(rel_abundance_df)]

column_order <- c('Genus', 'Met6527', 'Met7082', 'Met6522', 'Met7077', 'Met6506', 'Met6495', 'Met7098', 'Met7093', 'Met6511', 'Met6500', 'Met6516', 'Met6479', 'Met6490', 'Met8116', 'Met8121', 'Met6474', 'Met6484', 'Met7087')

filtered_order <- column_order[column_order %in% colnames(rel_abundance_df)]
rel_abundance_df_ordered <- rel_abundance_df[, filtered_order]

write.xlsx(rel_abundance_df_ordered, file = 'data_files/Vx_Genus_OTU.xlsx', rowNames = TRUE, colNames = TRUE)
```

```{r}
otu_table <- as.data.frame(otu_table(Vx_generaphy_filtered))

tax_table <- as.data.frame(tax_table(Vx_generaphy_filtered))

rownames(otu_table) <- rownames(tax_table)

otu_table_with_genus <- cbind(otu_table, Genus = tax_table$Genus)

write.csv(otu_table_with_genus, "data_files/otu_table_with_genus.csv", row.names = TRUE)
```

```{r}
rel_abundance_ps_vx <- subset_samples(rel_abundance_ps, site_specific == 'Vx' & library_id != "Met6532")

group_info <- sample_data(rel_abundance_ps_vx)$group_id

wilcox_results <- data.frame(Taxon = character(), p_value = numeric(), lower_ci = numeric(), upper_ci = numeric(), stringsAsFactors = FALSE)

#iterate over each taxa in rel_abundance_ps_vx
for (taxon in rownames(otu_table(rel_abundance_ps_vx))) {
  #extract abundance data for the current taxon
  taxon_abundance <- as.numeric(otu_table(rel_abundance_ps_vx)[taxon, ])
  
  #apply Wilcoxon rank-sum test for the current taxon with confidence intervals
  wilcox_result <- wilcox.test(taxon_abundance[group_info == "CCCA"],
                               taxon_abundance[group_info == "Control"],
                               conf.int = TRUE)
  
  #store result in a data frame
  result_row <- data.frame(Taxon = taxon, p_value = wilcox_result$p.value,
                           lower_ci = wilcox_result$conf.int[1],
                           upper_ci = wilcox_result$conf.int[2])
  
  wilcox_results <- bind_rows(wilcox_results, result_row)}

#apply Benjamini-Hochberg correction to all p-values
wilcox_results$adjusted_p_value <- p.adjust(wilcox_results$p_value, method = "BH")

#filter for significant results based on  adjusted p-values
differentially_abundant <- wilcox_results %>%
  filter(adjusted_p_value < 0.05)

print(differentially_abundant)

taxonomic_info <- data.frame(tax_table(rel_abundance_ps))
taxonomic_info$Taxon <- rownames(taxonomic_info)

#merge  differential abundance results with taxonomic information
differential_taxa <- merge(differentially_abundant, taxonomic_info, by = "Taxon", all.x = TRUE)

print(differential_taxa)
```

```{r}
rel_abundance_ps_vx <- subset_samples(rel_abundance_ps, site_specific == 'Vx' & library_id != "Met6532")

#extract group information
group_info <- sample_data(rel_abundance_ps_vx)$group_id

#create an empty data frame to store results
wilcox_results <- data.frame(Taxon = character(), p_value = numeric(), 
                             median_ccca = numeric(), median_control = numeric(),
                             iqr_ccca_lower = numeric(), iqr_ccca_upper = numeric(),
                             iqr_control_lower = numeric(), iqr_control_upper = numeric(),
                             stringsAsFactors = FALSE)

#iterate over each taxa in rel_abundance_ps_vx
for (taxon in rownames(otu_table(rel_abundance_ps_vx))) {
  #Extract abundance data for the current taxon
  taxon_abundance <- as.numeric(otu_table(rel_abundance_ps_vx)[taxon, ])
  
  #calculate median and IQR for each group
  ccca_abundance <- taxon_abundance[group_info == "CCCA"]
  control_abundance <- taxon_abundance[group_info == "Control"]
  
  ccca_median <- median(ccca_abundance)
  control_median <- median(control_abundance)
  
  ccca_iqr <- quantile(ccca_abundance, probs = c(0.25, 0.75))
  control_iqr <- quantile(control_abundance, probs = c(0.25, 0.75))
  
  #apply Wilcoxon rank-sum test for the current taxon
  wilcox_result <- wilcox.test(taxon_abundance[group_info == "CCCA"],
                               taxon_abundance[group_info == "Control"])
  
  #store the result in a data frame
  result_row <- data.frame(Taxon = taxon, p_value = wilcox_result$p.value,
                           median_ccca = ccca_median, median_control = control_median,
                           iqr_ccca_lower = ccca_iqr[1], iqr_ccca_upper = ccca_iqr[2],
                           iqr_control_lower = control_iqr[1], iqr_control_upper = control_iqr[2])
  
  wilcox_results <- bind_rows(wilcox_results, result_row)}

#apply Benjamini-Hochberg correction to all p-values
wilcox_results$adjusted_p_value <- p.adjust(wilcox_results$p_value, method = "BH")

#filter for significant results based on the adjusted p-values
differentially_abundant <- wilcox_results %>%
  filter(adjusted_p_value < 0.05)

#extract taxonomic information from the tax_table in rel_abundance_ps
taxonomic_info <- data.frame(tax_table(rel_abundance_ps))
taxonomic_info$Taxon <- rownames(taxonomic_info)
print("taxonomic_info:")
print(taxonomic_info)

#merge the differential abundance results with taxonomic information
differential_taxa <- merge(differentially_abundant, taxonomic_info, by = "Taxon", all.x = TRUE)

print("differential_taxa:")
print(differential_taxa)
```

```{r}
#extract the relative abundance data for Genus Corynebacterium (tax ID is 1716)
corynebacterium_rel_abundance = otu_table(rel_abundance_ps)["1716", ]

#convert to dataframe and merge with sample data
sample_data_df = data.frame(sample_data(rel_abundance_ps))
corynebacterium_rel_abundance_df = data.frame(t(corynebacterium_rel_abundance))
colnames(corynebacterium_rel_abundance_df) <- "corynebacterium_RA"
merged_df = cbind(sample_data_df, corynebacterium_rel_abundance_df)

merged_df$group_id = factor(merged_df$group_id, levels = c("CCCA", "Control"))

custom_colors <- c("#35274A", "#b8b8b8")

p = ggplot(merged_df, aes(x=group_id, y=corynebacterium_RA*100, color=group_id)) +
  geom_point(position=position_jitterdodge(dodge.width=0.75, jitter.width = 0.2), alpha = 0.7, size = 3) +
  geom_boxplot(aes(fill=group_id), alpha=0.6, position=position_dodge(width=0.75), width = 0.3) +
  scale_color_manual(values = custom_colors) +
  scale_fill_manual(values = custom_colors) +
  labs(title = "Corynebacterium", x = NULL, y = "Relative Abundance (%)", color = "Group", fill = "Group") +
  theme_minimal() +
  guides(color = FALSE, fill = FALSE) +
  stat_compare_means(
    aes(label = p.signif),
    comparisons = list(c("Control", "CCCA")),
    method = "wilcox.test",
    method.args = list(alternative = "two.sided", paired = FALSE),
    p.adjust.method = "BH",
    position = position_dodge(0.75),
    show.legend = FALSE,
    symnum.args = list(cutpoints = c(0.001, 0.005, 0.01), 
         symbols = c("*"))) +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    plot.title = element_text(size = 20),
    axis.title = element_text(size = 16),
    axis.text = element_text(size = 14))

print(p)

#ggsave("corynebacterium_relative_abundance_plot.png", plot = p, width = 3.5, height = 6, dpi = 300)
ggsave("figures/Figure2A.pdf", plot = p, width = 3.5, height = 6)


#calculate median and IQR of relative abundance for each group
summary_stats_by_group = aggregate(corynebacterium_RA ~ group_id, data = merged_df, FUN = function(x) c(median = median(x), IQR = IQR(x)))

summary_stats_by_group = cbind(summary_stats_by_group[1], summary_stats_by_group[[2]])

colnames(summary_stats_by_group) <- c("Group", "Median Relative Abundance", "IQR")

print(summary_stats_by_group)
```